name: Checking out rolldown and Building

env:
  DEBUG: "napi:*"
  RUST_BACKTRACE: full
  # https://github.com/nodejs/node/issues/51555#issuecomment-2290742072
  DISABLE_V8_COMPILE_CACHE: 1
  ROLLDOWN_REF: "v1.0.0-beta.47"

on:
  push:
    branches:
      - main

jobs:
  build-normal:
    if: ${{ false }}
    strategy:
      fail-fast: false
      matrix:
        settings:
          - host: ubuntu-latest
          - host: windows-latest

    name: build - ${{ matrix.settings.host }}
    runs-on: ${{ matrix.settings.host }}

    steps:
      - uses: actions/checkout@v6

      - name: setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: setup node
        uses: actions/setup-node@v6
        with:
          node-version: 22

      - name: clone rolldown
        run: |
          git clone --depth 1 --branch ${{ env.ROLLDOWN_REF }} https://github.com/rolldown/rolldown

      - name: cache node_modules
        uses: actions/cache@v4
        with:
          path: |
            rolldown/node_modules
          key: ${{ runner.os }}-node-rolldown-${{ hashFiles('rolldown/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-node-rolldown-

      - name: prepare rolldown
        run: |
          cd rolldown
          corepack enable
          pnpm install --frozen-lockfile --ignore-scripts

      - name: List .node files
        if: ${{ matrix.settings.host }} == "ubuntu-latest"
        run: |
          cd rolldown
          find node_modules -type f -name '*.node' -print

  build-msys:
    name: build - msys - ucrt64
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: false
          install: >-
            git
            curl
          pacboy: >-
            nodejs:p
            toolchain:p
            cmake:p
            rust:p

      - name: setup pnpm
        shell: msys2 {0}
        run: npm install -g pnpm

      - name: clone rolldown
        shell: msys2 {0}
        run: |
          git clone --depth 1 --branch $ROLLDOWN_REF https://github.com/rolldown/rolldown
      - name: cache node_modules
        uses: actions/cache@v4
        with:
          path: |
            rolldown/node_modules
          key: ${{ runner.os }}-ucrt64-node-rolldown-${{ hashFiles('rolldown/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-ucrt64-node-rolldown-

      - name: prepare rolldown
        shell: msys2 {0}
        run: |
          mkdir -p rolldown/dummy/rolldown-binding-builder
          cp rolldown/packages/rolldown/build-binding.ts rolldown/dummy/rolldown-binding-builder/build-binding.mjs
          cp patches/rolldown/package.json rolldown/dummy/rolldown-binding-builder

      - name: build rolldown binding
        shell: msys2 {0}
        run: |
          cd rolldown/dummy/rolldown-binding-builder
          npm install
          node ./build-binding.mjs
